set_property CFGBVS VCCO [current_design]
set_property CONFIG_VOLTAGE 3.3 [current_design]
#############SPI Configurate Setting##################
set_property BITSTREAM.CONFIG.SPI_BUSWIDTH 4 [current_design] 
set_property CONFIG_MODE SPIx4 [current_design] 
set_property BITSTREAM.CONFIG.CONFIGRATE 50 [current_design] 
############## clock define##################
create_clock -period 5 [get_ports sys_clk_p]
set_property PACKAGE_PIN R4 [get_ports sys_clk_p]
set_property IOSTANDARD DIFF_SSTL15 [get_ports sys_clk_p]
####################hdmi_out hdmi_in########################
set_property PACKAGE_PIN Y22 [get_ports vout_clk]
set_property PACKAGE_PIN V22 [get_ports {vout_data[0]}]
set_property PACKAGE_PIN Y18 [get_ports {vout_data[1]}]
set_property PACKAGE_PIN Y19 [get_ports {vout_data[2]}]
set_property PACKAGE_PIN W19 [get_ports {vout_data[3]}]
set_property PACKAGE_PIN W20 [get_ports {vout_data[4]}]
set_property PACKAGE_PIN Y21 [get_ports {vout_data[5]}]
set_property PACKAGE_PIN U21 [get_ports {vout_data[6]}]
set_property PACKAGE_PIN T21 [get_ports {vout_data[7]}]
set_property PACKAGE_PIN W21 [get_ports {vout_data[8]}]
set_property PACKAGE_PIN W22 [get_ports {vout_data[9]}]
set_property PACKAGE_PIN T20 [get_ports {vout_data[10]}]
set_property PACKAGE_PIN AB18 [get_ports {vout_data[11]}]
set_property PACKAGE_PIN AA18 [get_ports {vout_data[12]}]
set_property PACKAGE_PIN AA19 [get_ports {vout_data[13]}]
set_property PACKAGE_PIN AB20 [get_ports {vout_data[14]}]
set_property PACKAGE_PIN AA20 [get_ports {vout_data[15]}]
set_property PACKAGE_PIN AA21 [get_ports {vout_data[16]}]
set_property PACKAGE_PIN AB22 [get_ports {vout_data[17]}]
set_property PACKAGE_PIN AB21 [get_ports {vout_data[18]}]
set_property PACKAGE_PIN W17 [get_ports {vout_data[19]}]
set_property PACKAGE_PIN V17 [get_ports {vout_data[20]}]
set_property PACKAGE_PIN V20 [get_ports {vout_data[21]}]
set_property PACKAGE_PIN U20 [get_ports {vout_data[22]}]
set_property PACKAGE_PIN V19 [get_ports {vout_data[23]}]
set_property PACKAGE_PIN U22 [get_ports vout_de]
set_property PACKAGE_PIN T18 [get_ports vout_hs]
set_property PACKAGE_PIN Y17 [get_ports hdmi_nreset_v10]
set_property PACKAGE_PIN L18 [get_ports hdmi_nreset]
set_property PACKAGE_PIN R18 [get_ports vout_vs]
set_property PACKAGE_PIN H13 [get_ports hdmi_scl]
set_property PACKAGE_PIN G13 [get_ports hdmi_sda]

set_property IOSTANDARD LVCMOS33 [get_ports vout_clk]
set_property IOSTANDARD LVCMOS33 [get_ports {vout_data[*]}]
set_property IOSTANDARD LVCMOS33 [get_ports vout_de]
set_property IOSTANDARD LVCMOS33 [get_ports vout_hs]
set_property IOSTANDARD LVCMOS33 [get_ports hdmi_nreset]
set_property IOSTANDARD LVCMOS33 [get_ports hdmi_nreset_v10]
set_property IOSTANDARD LVCMOS33 [get_ports vout_vs]
set_property IOSTANDARD LVCMOS33 [get_ports hdmi_scl]
set_property IOSTANDARD LVCMOS33 [get_ports hdmi_sda]

set_property IOB TRUE [get_ports {vout_data[*]}]
set_property IOB TRUE [get_ports vout_de]
set_property IOB TRUE [get_ports vout_hs]
set_property IOB TRUE [get_ports vout_vs]

set_property SLEW FAST [get_ports {vout_data[*]}]
set_property SLEW FAST [get_ports vout_de]
set_property SLEW FAST [get_ports vout_hs]
set_property SLEW FAST [get_ports vout_vs]

set_property PACKAGE_PIN K18 [get_ports vin_clk]
set_property PACKAGE_PIN M20 [get_ports {vin_data[0]}]
set_property PACKAGE_PIN N20 [get_ports {vin_data[1]}]
set_property PACKAGE_PIN L21 [get_ports {vin_data[2]}]
set_property PACKAGE_PIN M21 [get_ports {vin_data[3]}]
set_property PACKAGE_PIN K19 [get_ports {vin_data[4]}]
set_property PACKAGE_PIN H17 [get_ports {vin_data[5]}]
set_property PACKAGE_PIN H18 [get_ports {vin_data[6]}]
set_property PACKAGE_PIN N22 [get_ports {vin_data[7]}]
set_property PACKAGE_PIN M22 [get_ports {vin_data[8]}]
set_property PACKAGE_PIN K22 [get_ports {vin_data[9]}]
set_property PACKAGE_PIN K21 [get_ports {vin_data[10]}]
set_property PACKAGE_PIN J22 [get_ports {vin_data[11]}]
set_property PACKAGE_PIN H22 [get_ports {vin_data[12]}]
set_property PACKAGE_PIN H20 [get_ports {vin_data[13]}]
set_property PACKAGE_PIN G20 [get_ports {vin_data[14]}]
set_property PACKAGE_PIN M17 [get_ports {vin_data[15]}]
set_property PACKAGE_PIN J16 [get_ports {vin_data[16]}]
set_property PACKAGE_PIN G17 [get_ports {vin_data[17]}]
set_property PACKAGE_PIN G18 [get_ports {vin_data[18]}]
set_property PACKAGE_PIN G15 [get_ports {vin_data[19]}]
set_property PACKAGE_PIN G16 [get_ports {vin_data[20]}]
set_property PACKAGE_PIN J19 [get_ports {vin_data[21]}]
set_property PACKAGE_PIN H19 [get_ports {vin_data[22]}]
set_property PACKAGE_PIN J20 [get_ports {vin_data[23]}]
set_property PACKAGE_PIN N19 [get_ports vin_de]
set_property PACKAGE_PIN N18 [get_ports vin_hs]
set_property PACKAGE_PIN J21 [get_ports hdmi_in_nreset]
set_property PACKAGE_PIN M18 [get_ports vin_vs]

set_property IOSTANDARD LVCMOS33 [get_ports vin_clk]
set_property IOSTANDARD LVCMOS33 [get_ports {vin_data[*]}]
set_property IOSTANDARD LVCMOS33 [get_ports vin_de]
set_property IOSTANDARD LVCMOS33 [get_ports vin_hs]
set_property IOSTANDARD LVCMOS33 [get_ports vin_vs]
set_property IOSTANDARD LVCMOS33 [get_ports hdmi_in_nreset]

set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets vout_clk_OBUF]

set_property DRIVE 12 [get_ports {vout_data[12]}]
set_property DRIVE 16 [get_ports vout_clk]
set_property DRIVE 12 [get_ports vout_de]
set_property DRIVE 12 [get_ports vout_hs]

############## key define#################################
set_property PACKAGE_PIN L19 [get_ports {key_in[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {key_in[0]}]

set_property PACKAGE_PIN L20 [get_ports {key_in[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {key_in[1]}]
set_property PACKAGE_PIN K17 [get_ports {key_in[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {key_in[2]}]

set_property PACKAGE_PIN J17 [get_ports {key_in[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {key_in[3]}]

create_clock -period 6.734 -name vin_clk -waveform {0.000 3.367} [get_ports vin_clk]
